### ISSUE TITLE
firefox desteği

### ISSUE THREAD

**Issue by alpers** [entriol/multisozlukextension#13]
selamlar,
Geliştirdiğiniz eklenti çok işime yarıyor. Teşekkürler. Firefox desteği için birkaç ufak değişiklik yaptım. Değişiklikleri içeren fork burada:
[https://github.com/alpers/multisozlukextension](https://github.com/alpers/multisozlukextension)
Markete sizin repo ve site bilginizle gönderdim. Siz yüklemek isterseniz ya da orada bulunmasını istermezseniz, ben kaldırırım. Bu kadar faydalı bir eklentinin firefoxta eksik kalmasını istemedim :)
[https://addons.mozilla.org/tr/firefox/addon/multi-s%C3%B6zl%C3%BCk-ext/](https://addons.mozilla.org/tr/firefox/addon/multi-s%C3%B6zl%C3%BCk-ext/)

**Comment by entriol** [comment]
Hiç problem değil, aslında bir süredir ben de Quantum ile birlikte Firefox'a geri döndüm. Eklentiyi bu yaz aylarında -yine sıfırdan- daha düzgün bir yol haritası ile kodlamayı düşünüyordum. Sonrasında Firefox marketine gönderecektim. Ama okul çok fazla zamanımı aldığından bir türlü başlayamadım. Belki bu itekleme başlamış olacağım 😊

**Comment by alpers** [comment]
Sevindim. Destek ihtiyacı olursa +1 sayabilirsiniz. İyi günler dilerim :)

**Comment by entriol** [comment]
Teşekkürler. Buraya yorum bırakacağım somut bir şeyler oluşmaya başlayınca
